/**
 * File based routing generator.
 *
 * Scans `src/frontend/pages/` and writes `src/frontend/pages.gen.ts` with a
 * static, deterministic route table:
 *
 * - `pages/index.ts`          -> `/`
 * - `pages/about/main.ts`     -> `/about`
 * - `pages/users/index.ts`    -> `/users`
 * - `pages/posts/[id].ts`     -> `/posts/:id`
 *
 * Routes are sorted static-first, then by path, so dynamic segments never
 * shadow static ones and the output is stable across filesystems.
 *
 * Run with: `deno task routes` (also part of `deno task dev`).
 */

const ROOT = "src/frontend/pages";
const OUTPUT = "src/frontend/pages.gen.ts";

/** A discovered page route. */
interface PageRoute {
  readonly route: string;
  readonly importPath: string;
}

/**
 * Recursively collects `.ts` files under a directory using native Deno APIs.
 *
 * @param dir Directory to walk.
 * @returns Relative file paths (POSIX separators) under {@link ROOT}.
 */
async function collectPageFiles(dir: string, prefix = ""): Promise<string[]> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(dir)) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory) {
      files.push(...await collectPageFiles(`${dir}/${entry.name}`, relative));
    } else if (entry.isFile && entry.name.endsWith(".ts")) {
      files.push(relative);
    }
  }
  return files;
}

/**
 * Converts a page file path into its HTTP route.
 *
 * @param relative Path relative to the pages root.
 * @returns Route pattern (Hono syntax).
 */
function toRoute(relative: string): string {
  let route = relative.replace(/\.ts$/, "");
  route = route.replace(/\/(main|index)$/, "");
  if (route === "index" || route === "main") route = "";
  route = route.replace(/\[(.+?)\]/g, ":$1");
  return `/${route}`.replace(/\/+$/, "") || "/";
}

/** Sorts static routes before dynamic ones, then alphabetically. */
function compareRoutes(a: PageRoute, b: PageRoute): number {
  const aDynamic = a.route.includes(":") ? 1 : 0;
  const bDynamic = b.route.includes(":") ? 1 : 0;
  if (aDynamic !== bDynamic) return aDynamic - bDynamic;
  return a.route.localeCompare(b.route);
}

const files = await collectPageFiles(ROOT);

const routes: PageRoute[] = files
  .map((relative) => ({ route: toRoute(relative), importPath: `./pages/${relative}` }))
  .sort(compareRoutes);

const imports = routes.map((page, i) => `import * as page${i} from "${page.importPath}";`);
const entries = routes.map((page, i) => `  { route: "${page.route}", module: page${i} },`);

const file = `// AUTO GENERATED by src/frontend/generate_routes.ts
// DO NOT EDIT — run \`deno task routes\` to regenerate.

${imports.join("\n")}

/** Static route table generated from src/frontend/pages/. */
export const pages = [
${entries.join("\n")}
] as const;
`;

await Deno.writeTextFile(OUTPUT, file);

// deno-lint-ignore no-console
console.log(`Generated ${routes.length} routes -> ${OUTPUT}`);
